/* Generated by Yosys 0.8+     148 (git sha1 e112d2f, clang 10.0.0 -fPIC -Os) */

(* src = "../files/demo.v:1" *)
module uut_always03(clock, in1, in2, in3, in4, in5, in6, in7, out1, out2, out3);
  (* src = "../files/demo.v:7" *)
  wire _00_;
  (* src = "../files/demo.v:7" *)
  wire _01_;
  (* src = "../files/demo.v:7" *)
  wire _02_;
  (* src = "../files/demo.v:7" *)
  wire _03_;
  (* src = "../files/demo.v:10" *)
  wire _04_;
  wire _05_;
  (* src = "../files/demo.v:3" *)
  input clock;
  (* src = "../files/demo.v:3" *)
  input in1;
  (* src = "../files/demo.v:3" *)
  input in2;
  (* src = "../files/demo.v:3" *)
  input in3;
  (* src = "../files/demo.v:3" *)
  input in4;
  (* src = "../files/demo.v:3" *)
  input in5;
  (* src = "../files/demo.v:3" *)
  input in6;
  (* src = "../files/demo.v:3" *)
  input in7;
  (* src = "../files/demo.v:4" *)
  output out1;
  reg out1;
  (* src = "../files/demo.v:4" *)
  output out2;
  reg out2;
  (* src = "../files/demo.v:4" *)
  output out3;
  reg out3;
  assign _04_ = ~(* src = "../files/demo.v:10" *) in1;
  assign _03_ = in2 ? (* src = "../files/demo.v:9" *) _04_ : in1;
  assign _01_ = in3 ? (* src = "../files/demo.v:12" *) out2 : _03_;
  assign _05_ = in5 ? (* src = "../files/demo.v:15" *) in6 : in7;
  assign _02_ = in4 ? (* src = "../files/demo.v:14" *) _05_ : out3;
  (* src = "../files/demo.v:7" *)
  always @(posedge clock)
      out1 <= _00_;
  (* src = "../files/demo.v:7" *)
  always @(posedge clock)
      out2 <= _01_;
  (* src = "../files/demo.v:7" *)
  always @(posedge clock)
      out3 <= _02_;
  assign _00_ = _03_ ^(* src = "../files/demo.v:19" *)  out2;
endmodule
